# Site settings
baseurl = "/"
languageCode = "es-PE"
title = "The Blue Hare"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"

[params]
	name = "The Blue Hare"
	description = "Un blog sobre corrupción, violencia y fallas del Estado"
	bio = "Por Kilder Urrutia"
	# Enter optionally your twitter account
	twitter = "Your Twitter account"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Sobre la pared de piedra"
	tweet = ""
	share = ""
	# 404 page
	title404 = "¡Aquí no!"
	subtitle404 = "¿Quizás en otra madriguera?"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/sefran12"
    linkedin  = "https://www.linkedin.com/"
